six2dez/reconftw

reconftw.sh
The removed if would never execute since `mkdir -p $called_fn_dir` will always create the `$dir` directory.
Not a big deal, just a small cleanup.
=> Remove unneeded code

install.sh
The install.sh script could hang during the install_apt() function when
apt-get expects user interaction, even though the -y argument is provided.
I added DEBIAN_FRONTEND="noninteractive" in front of the calls to
apt install to help prevent this.
Tested on fresh Ubuntu 18.04, Ubuntu 20.04 and Debian 10 docker images.
Resolves #289
=> Fix possible hang during install_apt()

reconftw.sh
**Fixed some grep commands logic and enhanced subjs performance by adding concurrent workers.**
#No need to use deliminator, makes more links dead
_Changed:_
`#cat js/url_extract_js.txt | cut -d '?' -f 1 | grep -iE "\.js$" | grep "$domain$" | anew -q js/jsfile_links.txt`
_To:_
`cp js/url_extract_js.txt js/jsfile_links.txt 
#Added threads to subjs, works like charm 
cat js/jsfile_links.txt | subjs -c 40 |grep "$domain" | anew -q .tmp/subjslinks.txt 
#Filtering js and other links into different files 
if [ -s .tmp/subjslinks.txt ] && cat .tmp/subjslinks.txt|egrep -iv ".(js|jpg|jpeg|woff|woff2|ttf|eot)"|anew -q js/nojs_links.txt 
#Adding js files found inside of jsfiles_links.txt by subjs into jsfile_links.txt 
if [ -s .tmp/subjslinks.txt ] && cat .tmp/subjslinks.txt|grep -iE "\.js"|anew -q …
=> Fixed and enhanced jscheck module

reconftw.sh
Added code to send the content of urls_by_ext.txt to bbrf. 
when i run `./reconftw.sh -a -d testfire.net` , there is none url path sent to bbrf, so added the code.
But i am sure if urls_by_ext.txt is good enough cause there is quite a lot of files containing urls
=> bbrf url add urls_by_ext.txt

reconftw.sh
I think the correct syntax is: `./uDork.sh host.com -u all` **NOT all.txt**
=> Udork invalid syntax "all.txt"

Docker/01_nodoc, Docker/Dockerfile, README.md, install.sh
There are 4 major changes in this PR.
1. Removed Golang configuration from Dockerfile.
Rationale: Initially, both Dockerfile & `install.sh` were fetching Golang version dynamically. However, in v2.1.4 `install.sh` was changed & Golang version was statically defined. It might happen that Dockerfile installs Golang only for `install.sh` to remove & re-install a different version. Better to just let `install.sh` configure Golang. 
2. Changed `install.sh` to symlink Golang binary instead of copy it.
Rationale: This is a space saving measure initially implemented in Dockerfile. Since Dockerfile is not configuring Golang anymore I decided to modify `install.sh`
3. Added file `01_nodoc` to `Docker/`
Rationale: This file is a `dpkg` configuration file which tells `apt` to ignore docs & man-pages …
=> Docker improvements & optimisations

install.sh
I mistakenly made the same Pull Request to main branch. Apologies.
`gowitness` fails to install with `404 module not found` error in the "Running: Installing Golang tools" stage.
You can confirm this in the CI workflow logs.
However, gowitness then successfully installs in the "Running: Double check for installed tools" stage.
I suspect that the `GO111MODULE` variable is getting set to on somewhere in between - since setting this variable removes the error in the initial stage.
=> fix gowitness install error

install.sh
Changed fuzz_wordlist URL 
from: https://media.githubusercontent.com/media/six2dez/OneListForAll/main/onelistforallmicro.txt 
to: https://raw.githubusercontent.com/six2dez/OneListForAll/main/onelistforallmicro.txt
=> Update onelistforallmicro.txt URL

Docker/Dockerfile
Added `'/root/.cargo/bin'` to $PATH to fix https://github.com/six2dez/reconftw/issues/522#issuecomment-1264745551
=> Fix ripgen not installed in Docker container

reconftw.sh
This fixes the logic for sending the output zip to subscribers via notify. 
Currently, we assume the output path is the same as `$SCRIPTPATH`, but this is a bad assumption. Anyone following [Data Keep](https://github.com/six2dez/reconftw#data-keep) would run into this issue since it implies the creation of a custom `/Recon` output directory. And I believe `$dir_output=$SCRIPTPATH` in the case of defaults (maybe double check this) so it shouldn't cause any issues for users who are not setting a custom output location.
@six2dez WDYT? 👀
=> feat: support custom output path in notify flow

install.sh
- `byp4xx `is installed through `go install` and not through the git repository.
- There was an entry in the git repo section that was clearly a forgotten work in progress. It was seemingly copied from the regulator key on the line above.
=> refactor: unused entry for git repository install section

reconftw.sh
add urless to remove duplicate or common lib js files.
example result:
```diff
http://redacted.com/resource/geetest_webuploader.js
- http://redacted.com/resource/jquery.min.js
- http://redacted.com/resource/plugin/jquery-ui.js
http://redacted.com/resource/plugin/swfupload/swfupload-total.js?v=20170908401
http://redacted.com/dhd/js/main.js?v=1507534712
- http://redacted.com/dhd/js/main.js?v=1507534719
- http://redacted.com/dhd/js/main.js?v=1507534721
```
=> refactor: add urless for js/url_extract_js.txt

reconftw.sh
sort the results of fuzzing_full.txt for better readability and quick discovery of interesting results.
example result:
```
504 167 https://redacted.com:443/mod_dosevasive
301 0 https://redacted.com:443/admin#
200 189979 https://redacted.com:443/monitor
200 91343 https://redacted.com:443/apidoc
200 15 https://redacted.com:443/h
200 9 https://redacted.com:443/actuator/healthcheck
```
=> refactor: numeric sort fuzzing_full.txt

Docker/Dockerfile
The tools installation are skipped because for the new interactive options in install.sh script. I've used echo to choose '**1**' from prompt and start reconFTW installation from the script. Check #692
=> Update Dockerfile to install all reconFTW tool

README.md
- Improved Docker documentation
- **Removed dollar sign:** this caused users to copy a command that includes a dollar sign (which of course doesn't work and requires manual removal)
- Added note to example usage header
- Fixed incorrect image
=> docs(readme): improve Docker documentation

reconftw.sh
Get open ports and vulnerabilities of IPs using the [shodan db](https://internetdb.shodan.io/) no need of a shodan API key. 
Compared to the current `portscan` implementation this also gets the CVEs and CPEs in a completely stealth way, then save the results in a json file.
=> Shodan vulns and ports

install.sh, reconftw.sh, requirements.txt
So I've updated **brutespray** , **waymore,** **xnLinkFinder** install with their new installation methods.
I have updated the instalaltion checks for the above.
I have updated the calling of the tools since they can now be called globally via path binary instead of using python.
I have updated the Post install message to include Github tokens and waymore config path.
=> Tool installation fixes mainly

reconftw.sh
remove additional $ causing the dirs to fail creation
=> fix iis shortname scanner dir creations

reconftw.sh
Please feel free to just copy and paste the addition rather than accept the PR if you prefer.
I find these two tools are often not installed, and the 'installed tools check' doesn't highlight that, so I only discovered they were missing after kicking off an actual scan. Only a minor change, but a QoL improvement for me at least.
I appreciate your work on this tool, 
Thanks.
=> Adding Metafinder & Whois to installed tools check.

reconftw.sh
Added notification for start and end of multi recon using organization name. Previously a user running a command like `./reconftw -m hackerone -l hackerone.txt -r` and using soft notifications only (start and end only) would not get any notifcations
=> Add soft notfication to multi recon mode

.github/workflows/tests.yml, README.md, reconftw.sh
Related to #907. This PR:
- Add option `--check-tools` that will make `./reconftw.sh` exit (with a value greater than 0) if one or more tools are missing. Required for the GitHub workflow.
- This change also unify the path that is taken when using the `-h, --help` options or when no operation mode are provided (meaning that any execution will always reach the final `case $opt_mode`).
- Add a GitHub workflow to test the `./install.sh` script and make sure that all the tools installs properly ([on the available runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)).
=> Add --check-tools option and GitHub workflow

install.sh, reconftw.sh
Related to #907. This PR:
- Fix Golang download logic. After adding #920, I notice that the download logic did not yield the expected result on macOS (it was downloading the Linux ARM version). I removed the switch case statement for the arch detection, and move the logic directly in the switch case statement for the download. The resulting switch case should be compatible with Linux and macOS ARM-based system.
- Fix macOS (homebrew) dependencies. Many of the formulae listed were unused or did not exist at all.
- Add the `--formula` flag to remove warnings.
- Remove the `chromium` cask as chromium is provided (downloaded) by nuclei.
- Fix macOS path initialization. Since the introduction of Apple Silicon, homebrew installation location varies.
- Made the script use the `brew --prefix` …
=> Fix macos support

install.sh, reconftw.cfg, reconftw.sh
Related to #907. This PR:
- Fix Debian/Ubuntu (apt) dependencies.
- Remove the `chromium-browser` package as chromium is provided (downloaded) by nuclei.
- Split the dependencies for `chromium` to be compatible with various Ubuntu versions. This address the compatibility issue with Ubuntu 24.04 mentioned in #907.
- Use `apt-get` as `apt` should not be use for scripting.
- Add `~/.cargo/bin` in path (Rust) in `reconftw.cfg`. After adding #920, I noticed that one of the tools was missing. This was due to the `.bashrc` file not being reloaded after running `./install.sh`. Since the Golang environment variables are added in this file, I did the same for Cargo/Rust.
- Add missing tools in tools check. Some tools check were missing from `./reconftw.sh`. This help to detect if`./install.sh` …
=> Fix Debian/Ubuntu support and others install fixes

install.sh, reconftw.sh
Related to #907. This PR:
- Remove duplicate testssl repository. The `testssl.sh` tool was install twice, once as `testssl` and a second time as `testssl.sh`. This fix rename the first one, and remove the second one, remaining compatible with the paths in `./reconftw.sh`.
- Fix ffufPostprocessing branch name. ffufPostprocessing uses `master`, not `main`.
- Restore special handling for trufflehog. This feature was present in the past but was removed by c46277a486b12fd0dbeeab16844d11ae996f2228.
- Copy gf patterns instead of moving. This is consistent with the special configurations section bellow.
=> Miscellaneous fixes

reconftw.sh
The $NUCLEI_FLAGS which includes `-silent -t /home/kleoz/nuclei-templates/ -retries 2` by default in the config , if put before the -severity flag it overwrites t , it needs to be after the severity flag like this:
`nuclei -severity "$crit" -nh -rl "$NUCLEI_RATELIMIT" "$NUCLEI_FLAGS" "$NUCLEI_EXTRA_ARGS" -j -o "nuclei_output/${crit}_json.txt" <.tmp/webs_nuclei.txt `
=> Fix Nuclei Severity Filters

reconftw.sh
Quick and dirty fix for fuzzparams template folder, nuclei no longer uses the archived repo , it instead uses nuclei-templates/dast for fuzzing.
I haven't touched the repo cloning, variables or axiom to not mess it up since I don't use it. This is a quick fix that uses the appropriate template path for fuzzparams on non-axiom scans.
=> fix fuzzparams

install.sh, reconftw.sh
This PR updates the installation step for **misconfig-mapper** to reflect recent changes in their upstream repository. The previous method no longer works due to modifications in their install script or repo structure.
- Updated the install logic/command for misconfig-mapper
- Ensured compatibility with the latest version from the upstream repository
The upstream project changed their installation process, which broke our current setup. This fix ensures a smooth installation using the updated method.
=> fix(install): update misconfig-mapper install step due to upstream changes
