- reconftw.sh
- update.sh
Adding an auto updater for used tools.
> Update used tools v0.0.1

- reconftw.sh
- update.sh
If the recon process is broken. ReconFtw will start from the last stopping point
> Support continue recon processing 

- update.sh
> updat script v0.0.2

- install.sh
During Installation, I found that **Interlace** and **LinkFinder** setup cannot be run from the absolute path you need to be in the same directory and was getting an issue with DNSGEN Installation without Sudo access.
Both of them are tried to be resolved!
> Resolved Some Issues

- install.sh
install_apt() failed due to an non-existing package name
> Update.sh (removed python-pip)

- reconftw.sh
Need to be improved by scanning all probed domains
> implementig pymeta v0.1.0

- reconftw.sh
list of urls:
https://target.com/config.js
https://target.com/config2.js?ver=2
cat urls | cut -d '?' -f 1 and then egrep -i "\.js$" will include both urls.
> JS grepping

- README.md
This PR adds a section inside `README.md` to actively keep the official repo updated along with private keys/data in a private repository.
> Add Data-Keep section

- reconftw.cfg
- reconftw_axiom.sh
This allows for reconFTW to do the non-axiom OSINT stuff to get done BEFORE the cluster launches.  In the case of a large project OSINT could take days...
> Added Axiom Fleet start/stop

- README.md
- install.sh
- reconftw.sh
- Naabu timeout added
- Readme fix
- Installer fix
> Small fixes

- install.sh
- reconftw.sh
- reconftw_axiom.sh
- Temp fix for analyticsrelationships
- Improvements on recursive subdomains search
> Fixed analyticsrelationship && improved recursive search

- README.md
- reconftw.sh
> Revert "Duplicate ssrf skiped"

- Docker/Dockerfile
- README.md
Remove ▶
docker auto exec with volumes.
> Docker auto exec with volumes

- README.md
> Use docker main tag instead of latest

- install.sh
- reconftw.cfg
- reconftw.sh
- reconftw_axiom.sh
In this commit it has been added:
- 
- First approach to generating custom lists via robots.txt file.
- Updated the gotator command for version 1 of the tool.
> First approach to roboxtractor and update of gotator command

- .github/workflows/docker_nightly.yml
Nightly build and push to dockerhub
You need to add those secrets in the repo settings
> DockerCI : Nightly build and push to dokcerhub

- install.sh
- requirements.txt
Removed using gotwitness through binary
> Removed running gotwitness through binary, removed webscreenshot

- install.sh
There is an issue with the installation of most (if not all) Python modules - at least in the Docker container. 
I have documented the issue & the proposed fix in more detail in #434
> Fix for python modules

- reconftw.sh
Trap Ctrl+C and skip the current function
> Trap Ctrl+C

- reconftw.sh
More specific grepping using 'awk'
> fix h8_results grepping issue

- install.sh
- reconftw.cfg
- reconftw.sh
> Added HTTP Request Smuggling

- install.sh
- reconftw.cfg
- reconftw.sh
> Web cache poisoning added

- install.sh
Without changing functionality, this commit makes a few chages in order to avoid some common pitfall in bash scripts.
> harden bash variable use in install script

- reconftw.sh
Just quick change to the `resolvers_update_quick_axiom()` function to bring it in line with the other resolver changes.
> Update to resolver patch

- install.sh
https://gitlab.com/exploit-database/exploitdb
> ExploitDB was moved to gitlab

- README.md
- Terraform/files/reconftw.cfg
- reconftw.cfg
Hi. Thanks for including my subdomain wordlist. I am honored!
Though I would really appreciate it if my name stayed in the filename, in case people were to distribute it directly from reconftw without knowing its source :)
Keep up the great work! 🙏
> Add credit on subdomain wordlist

- README.md
- Terraform/README.md
- Fixed Markdownlint issues
- Fixed spelling/grammar mistakes
- Fix incorrect numbered lists
- Use proper code blocks
@six2dez Considering a lot of lines have changed, it may require additional testing. I've done my part (it works afaik), but some parts are up to you for checking, for example the headers. For a preview, see: https://github.com/AnonymousWP/reconftw/blob/docs/README.md.
More is planned regarding documentation (and maybe Docker-related stuff too).
> docs(readme): refactor documentation for reconFTW and Terraform/Ansible

- web/web/settings.py
Added `ALLOWED_HOSTS = ['*']` => allow any host
> Fix Error DisallowedHost at / Invalid HTTP_Host Header

- reconftw.sh
Curl [ipapi.co](https://ipapi.co/) to get some info of an IP such as: city, region, country, latitude, longitude. Save the output in `/hosts/geoip.txt` and `/hosts/geoip.json`.
Added also connection check.
> Ip geo_info (from dev)

- reconftw.sh
fixing the case of mantra command.
> Fix Mantra is not found

- reconftw.sh
Paths were missing / seperators
> Fix Apileak paths

- reconftw.sh
Brutespray is now global , no need for directory or calling brutespray/main , can be called directly.
> Fix brutespray Calling

- reconftw.sh
-fuzz flag required now for fuzzing
> Fix nuclei fuzzing

- reconftw.sh
- requirements.txt
Added https://github.com/iambouali/p1radup to remove duplicate params from the same host , to avoid testing for duplicate params over and over again , optimizing speed and resources.
> Optimize vuln scan speed and efficiency

- Proxmox/README.md
- Proxmox/reconftw_prox_deploy.sh
Added script to deploy a debian11 machine with reconFTW deployed. debian11 is chosen because debian12 has problems with python packages...
> Add proxmox Deployment Script

- reconftw.sh
Fix sub_dns() extract ips from subdomains_ips.txt
> Fix sub_dns() extract ips from subdomains_ips.txt

- install.sh
- reconftw.sh
Fix urlfinder flag
add jsbeautifier lib
> Few small fixes
